spring:
  application:
    name: transaction
  config:
    import: optional:configserver:http://localhost:8888 # Config server URL. Optional means if this microservise not find the config on config server then it will not fail to start


