package pl.zeto.backend.VMC.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import pl.zeto.backend.VMC.model.Currency;
import pl.zeto.backend.VMC.repository.CurrencyRepo;

@Configuration
public class LoadDatabase {

    @Bean
    CommandLineRunner initDatabase(CurrencyRepo repository) {
        return args -> {
            if (repository.count() == 0) {
                // Dodaj waluty do bazy danych
                repository.save(new Currency("AED", "dirham arabski"));
                repository.save(new Currency("AFN", "afgani"));
                repository.save(new Currency("ALL", "lek albański"));
                repository.save(new Currency("AMD", "dram armeński"));
                repository.save(new Currency("ANG", "gulden antylski"));
                repository.save(new Currency("AOA", "kwanza angolska"));
                repository.save(new Currency("ARS", "peso argentyńskie"));
                repository.save(new Currency("AUD", "dolar australijski"));
                repository.save(new Currency("AWG", "florin arubański"));
                repository.save(new Currency("AZN", "manat azerski"));
                repository.save(new Currency("BAM", "marka konwertowalna"));
                repository.save(new Currency("BBD", "dolar Barbadosu"));
                repository.save(new Currency("BDT", "taka bengalska"));
                repository.save(new Currency("BGN", "lew bułgarski"));
                repository.save(new Currency("BHD", "dinar bahrański"));
                repository.save(new Currency("BIF", "frank burundyjski"));
                repository.save(new Currency("BMD", "dolar bermudzki"));
                repository.save(new Currency("BND", "dolar brunejski"));
                repository.save(new Currency("BOB", "boliviano boliwijskie"));
                repository.save(new Currency("BRL", "real brazylijski"));
                repository.save(new Currency("BSD", "dolar bahamski"));
                repository.save(new Currency("BTN", "ngultrum butański"));
                repository.save(new Currency("BWP", "pula botswańska"));
                repository.save(new Currency("BYN", "rubel białoruski"));
                repository.save(new Currency("BZD", "dolar belizeński"));
                repository.save(new Currency("CAD", "dolar kanadyjski"));
                repository.save(new Currency("CDF", "frank kongijski"));
                repository.save(new Currency("CHF", "frank szwajcarski"));
                repository.save(new Currency("CLP", "peso chilijskie"));
                repository.save(new Currency("CNY", "juan chiński"));
                repository.save(new Currency("COP", "peso kolumbijskie"));
                repository.save(new Currency("CRC", "colon kostarykański"));
                repository.save(new Currency("CVE", "escudo kabowerdyjskie"));
                repository.save(new Currency("CZK", "korona czeska"));
                repository.save(new Currency("DJF", "frank dżibutyjski"));
                repository.save(new Currency("DKK", "korona duńska"));
                repository.save(new Currency("DOP", "peso dominikańskie"));
                repository.save(new Currency("DZD", "dinar algierski"));
                repository.save(new Currency("EGP", "funt egipski"));
                repository.save(new Currency("ERN", "nakfa erytrejska"));
                repository.save(new Currency("ETB", "birr etiopski"));
                repository.save(new Currency("EUR", "euro"));
                repository.save(new Currency("FJD", "dolar fidżijski"));
                repository.save(new Currency("FKP", "funt falklandzki"));
                repository.save(new Currency("GBP", "funt szterling"));
                repository.save(new Currency("GEL", "lari gruzińskie"));
                repository.save(new Currency("GHS", "cedi ghańskie"));
                repository.save(new Currency("GIP", "funt gibraltarski"));
                repository.save(new Currency("GMD", "dalasi gambijskie"));
                repository.save(new Currency("GNF", "frank gwinejski"));
                repository.save(new Currency("GTQ", "quetzal gwatemalski"));
                repository.save(new Currency("GYD", "dolar gujański"));
                repository.save(new Currency("HKD", "dolar hongkoński"));
                repository.save(new Currency("HNL", "lempira honduraska"));
                repository.save(new Currency("HRK", "kuna chorwacka"));
                repository.save(new Currency("HTG", "gourde haitańskie"));
                repository.save(new Currency("HUF", "forint węgierski"));
                repository.save(new Currency("IDR", "rupia indonezyjska"));
                repository.save(new Currency("ILS", "nowy szekel izraelski"));
                repository.save(new Currency("INR", "rupia indyjska"));
                repository.save(new Currency("IQD", "dinar iracki"));
                repository.save(new Currency("IRR", "rial irański"));
                repository.save(new Currency("ISK", "korona islandzka"));
                repository.save(new Currency("JMD", "dolar jamajski"));
                repository.save(new Currency("JOD", "dinar jordański"));
                repository.save(new Currency("JPY", "jen japoński"));
                repository.save(new Currency("KES", "szyling kenijski"));
                repository.save(new Currency("KGS", "som kirgiski"));
                repository.save(new Currency("KHR", "riel kambodżański"));
                repository.save(new Currency("KMF", "frank komoryjski"));
                repository.save(new Currency("KPW", "won północnokoreański"));
                repository.save(new Currency("KRW", "won południowokoreański"));
                repository.save(new Currency("KWD", "dinar kuwejcki"));
                repository.save(new Currency("KYD", "dolar kajmański"));
                repository.save(new Currency("KZT", "tenge kazachskie"));
                repository.save(new Currency("LAK", "kip laotański"));
                repository.save(new Currency("LBP", "funt libański"));
                repository.save(new Currency("LKR", "rupia lankijska"));
                repository.save(new Currency("LRD", "dolar liberyjski"));
                repository.save(new Currency("LSL", "loti Lesoto"));
                repository.save(new Currency("LTD", "dolar litewski"));
                repository.save(new Currency("LVL", "łat łotewski"));
                repository.save(new Currency("LYD", "dinar libijski"));
                repository.save(new Currency("MAD", "dirham marokański"));
                repository.save(new Currency("MDL", "lej mołdawski"));
                repository.save(new Currency("MGA", "ariary malgaski"));
                repository.save(new Currency("MKD", "denar macedoński"));
                repository.save(new Currency("MMK", "kyat birmański"));
                repository.save(new Currency("MNT", "tugrik mongolski"));
                repository.save(new Currency("MOP", "pataca makaujska"));
                repository.save(new Currency("MRO", "ouguiya mauretańska"));
                repository.save(new Currency("MUR", "rupia maurytyjska"));
                repository.save(new Currency("MVR", "rufiyaa malediwska"));
                repository.save(new Currency("MWK", "kwacha malawijska"));
                repository.save(new Currency("MXN", "peso meksykańskie"));
                repository.save(new Currency("MYR", "ringgit malezyjski"));
                repository.save(new Currency("MZN", "metical mozambicki"));
                repository.save(new Currency("NAD", "dolar namibijski"));
                repository.save(new Currency("NGN", "naira nigeryjska"));
                repository.save(new Currency("NIO", "cordoba nikaraguańska"));
                repository.save(new Currency("NOK", "korona norweska"));
                repository.save(new Currency("NPR", "rupia nepalska"));
                repository.save(new Currency("NZD", "dolar nowozelandzki"));
                repository.save(new Currency("OMR", "rial omański"));
                repository.save(new Currency("PAB", "balboa panamska"));
                repository.save(new Currency("PEN", "sol peruwiański"));
                repository.save(new Currency("PGK", "kina papuaska"));
                repository.save(new Currency("PHP", "peso filipińskie"));
                repository.save(new Currency("PKR", "rupia pakistańska"));
                repository.save(new Currency("PLN", "złoty polski"));
                repository.save(new Currency("PYG", "guarani paragwajskie"));
                repository.save(new Currency("QAR", "rial katarski"));
                repository.save(new Currency("RON", "lej rumuński"));
                repository.save(new Currency("RSD", "dinar serbski"));
                repository.save(new Currency("RUB", "rubel rosyjski"));
                repository.save(new Currency("RWF", "frank rwandyjski"));
                repository.save(new Currency("SAR", "rial saudyjski"));
                repository.save(new Currency("SBD", "dolar salomoński"));
                repository.save(new Currency("SCR", "rupia seszelska"));
                repository.save(new Currency("SDG", "funt sudański"));
                repository.save(new Currency("SEK", "korona szwedzka"));
                repository.save(new Currency("SGD", "dolar singapurski"));
                repository.save(new Currency("SHP", "funt św. Heleny"));
                repository.save(new Currency("SLL", "leone sierraleoński"));
                repository.save(new Currency("SOS", "szyling somalijski"));
                repository.save(new Currency("SRD", "dolar surinamski"));
                repository.save(new Currency("SSP", "funt południowosudański"));
                repository.save(new Currency("STD", "dobra saotomejska"));
                repository.save(new Currency("SVC", "kolon salwadorski"));
                repository.save(new Currency("SYP", "funt syryjski"));
                repository.save(new Currency("SZL", "lilangeni Suazi"));
                repository.save(new Currency("SEK", "korona szwedzka"));
                repository.save(new Currency("TJS", "somoni tadżyckie"));
                repository.save(new Currency("TND", "dinar tunezyjski"));
                repository.save(new Currency("TOP", "paanga tongańska"));
                repository.save(new Currency("TRY", "lira turecka"));
                repository.save(new Currency("TTD", "dolar trynidadzki"));
                repository.save(new Currency("TWD", "nowy dolar tajwański"));
                repository.save(new Currency("TZS", "szyling tanzański"));
                repository.save(new Currency("UAH", "hrywna ukraińska"));
                repository.save(new Currency("UGX", "szyling ugandyjski"));
                repository.save(new Currency("USD", "dolar amerykański"));
                repository.save(new Currency("UYU", "peso urugwajskie"));
                repository.save(new Currency("UZS", "som uzbecki"));
                repository.save(new Currency("VEF", "bolivar wenezuelski"));
                repository.save(new Currency("VND", "dong wietnamski"));
                repository.save(new Currency("VUV", "vatu vanuackie"));
                repository.save(new Currency("WST", "tala samoańska"));
                repository.save(new Currency("XAF", "frank CFA"));
                repository.save(new Currency("XCD", "dolar wschodniokaraibski"));
                repository.save(new Currency("XOF", "frank CFA"));
                repository.save(new Currency("XPF", "frank CFP"));
                repository.save(new Currency("YER", "rial jemenicki"));
                repository.save(new Currency("ZAR", "rand południowoafrykański"));
                repository.save(new Currency("ZMK", "kwacha zambijska"));
                repository.save(new Currency("ZWL", "dolar Zimbabwe"));
                // Dodaj więcej walut według potrzeb
            }
        };
    }
}