services:


  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
#  postgres:
#    driver: bridge
  zipkin:
    driver: bridge
  proxy:
    external: true
  keycloak:

#volumes:
#  postgres:
#  pgadmin:
#  postgres_data:
#  postgresql:


