services:
  postgres_keycloak:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"

  postgres_paypal:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=paypal
    ports:
      - "5433:5432"

  postgres_transaction:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=transaction
    ports:
      - "5434:5432"

  postgres_currencies:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=currencies
    ports:
      - "5435:5432"

  postgres_currency_accounts:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=currency_accounts
    ports:
      - "5436:5432"


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DB_URL=postgres://postgres:admin@localhost:5432/keycloak
    ports:
      - "8080:8080"
    command: ["start-dev"]
    depends_on:
      - postgres_keycloak

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  zipkin:
    driver: bridge
  proxy:
    external: true
  keycloak: