#spring.application.name=discovery
#spr.app.na
#
#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false

spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888 # Config server URL. Optional means if this microservise not find the config on config server then it will not fail to start
