spring:
  application:
    name: currencies
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/currencies
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ # Eureka server URL 8761 because its the port of discovery server


server:
  port: 8073
  servlet:
    context-path: /api

management:
  tracing:
    sampling:
      probability: 1.0