spring:
  application:
    name: currencies
  jpa:
    hibernate:
      #      Pierwsze uruchomienie
      ddl-auto: create
      #      update - po pierwszym uruchomieniu
#      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    # Lokalnie przez dockera
    #    url: jdbc:postgresql://localhost:5435/currencies
    #    username: postgres
    #    password: admin
    # Przez Azure
    url: jdbc:postgresql://postgres-currencies.postgres.database.azure.com:5432/postgres
    username: postgres
    password: admin123@
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ # Eureka server URL 8761 because its the port of discovery server


server:
  port: 8073
  servlet:
    context-path: /api

management:
  tracing:
    sampling:
      probability: 1.0