spring:
  jpa:
    hibernate:
#      Pierwsze uruchomienie
#      ddl-auto: create
#      update - po pierwszym uruchomieniu
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
# Lokalnie przez dockera
#    url: jdbc:postgresql://localhost:5437/gateway
#    username: postgres
#    password: admin
# Przez Azure
    url: jdbc:postgresql://postgres-gateway.postgres.database.azure.com:5432/postgres
    username: postgres
    password: admin123@
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server # Jeśli chodzi o błąd No instances found of configserver (config-server) to bug i tyle wysztko działa :)
    gateway:
      mvc:
        routes:
          - id: transaction-service
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/transactions/**
          - id: paypal-service
            uri: http://localhost:8071
            predicates:
              - Path=/api/v1/paypal/**
          - id: currencies-service
            uri: http://localhost:8073
            predicates:
              - Path=/api/v1/currencies/**
          - id: currency-accounts-service
            uri: http://localhost:8072
            predicates:
              - Path=/api/v1/currencyAccounts/**

eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0