package pl.kantor.backend.MVC.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import pl.kantor.backend.MVC.model.Currency;
import pl.kantor.backend.MVC.repository.CurrencyRepo;

@Configuration
public class LoadDatabase {

    @Bean
    CommandLineRunner initDatabase(CurrencyRepo repository) {
        return args -> {
            if (repository.count() == 0) {
                repository.save(new Currency("ZAR", "Rand"));
                repository.save(new Currency("NPR", "Rupia nepalska"));
                repository.save(new Currency("LBP", "Funt Libański"));
                repository.save(new Currency("SVC", "Colón salwadorski"));
                repository.save(new Currency("GMD", "Dalasi"));
                repository.save(new Currency("CHF", "Frank szwajcarski"));
                repository.save(new Currency("BMD", "Dolar Bermudzki"));
                repository.save(new Currency("RWF", "Frank rwandyjski"));
                repository.save(new Currency("BRL", "Real Brazylijski"));
                repository.save(new Currency("PKR", "Rupia pakistańska"));
                repository.save(new Currency("LAK", "Kip"));
                repository.save(new Currency("JPY", "Jen"));
                repository.save(new Currency("PGK", "Kina"));
                repository.save(new Currency("TZS", "Szyling tanzański"));
                repository.save(new Currency("MOP", "Pataca"));
                repository.save(new Currency("UGX", "Szyling ugandyjski"));
                repository.save(new Currency("TJS", "Somoni"));
                repository.save(new Currency("SLL", "Leone"));
                repository.save(new Currency("RSD", "Dinar serbski"));
                repository.save(new Currency("CLP", "Peso Chilijskie"));
                repository.save(new Currency("AED", "UAE Dirham"));
                repository.save(new Currency("TMT", "Manat turkmeński"));
                repository.save(new Currency("EUR", "Euro"));
                repository.save(new Currency("MNT", "Tugrik"));
                repository.save(new Currency("MYR", "Ringgit"));
                repository.save(new Currency("ANG", "Gulden antylski"));
                repository.save(new Currency("KWD", "Dinar kuwejcki"));
                repository.save(new Currency("MRU", "Ugija"));
                repository.save(new Currency("DZD", "Dinar algierski"));
                repository.save(new Currency("NZD", "Dolar nowozelandzki"));
                repository.save(new Currency("HTG", "Gourde"));
                repository.save(new Currency("AMD", "Dram"));
                repository.save(new Currency("ZWL", "Dolar Zimbabwe"));
                repository.save(new Currency("MZN", "Metical"));
                repository.save(new Currency("JOD", "Dinar jordański"));
                repository.save(new Currency("XAF", "CFA Frank BEAC"));
                repository.save(new Currency("CRC", "Colón"));
                repository.save(new Currency("FKP", "Funt Falklandzki"));
                repository.save(new Currency("BGN", "Lew"));
                repository.save(new Currency("KHR", "Riel kambodżański"));
                repository.save(new Currency("ERN", "Nakfa"));
                repository.save(new Currency("MXN", "Peso Meksykańskie"));
                repository.save(new Currency("XSU", "Sucre"));
                repository.save(new Currency("SDG", "Funt sudański"));
                repository.save(new Currency("XOF", "CFA Frank BCEAO"));
                repository.save(new Currency("BND", "Dolar Brunejski"));
                repository.save(new Currency("SSP", "Funt południowosudański"));
                repository.save(new Currency("USD", "Dolar amerykański"));
                repository.save(new Currency("KPW", "Won północnokoreański"));
                repository.save(new Currency("BSD", "Dolar Bahamski"));
                repository.save(new Currency("BIF", "Frank Burundyjski"));
                repository.save(new Currency("GEL", "Lari"));
                repository.save(new Currency("MMK", "Kiat"));
                repository.save(new Currency("UZS", "Sum"));
                repository.save(new Currency("AZN", "Manat Azerbejdżański"));
                repository.save(new Currency("XCD", "Dolar wschodniokaraibski"));
                repository.save(new Currency("HNL", "Lempira"));
                repository.save(new Currency("KGS", "Som"));
                repository.save(new Currency("TRY", "Lira turecka"));
                repository.save(new Currency("CNY", "Renminbi"));
                repository.save(new Currency("UYU", "Peso urugwajskie"));
                repository.save(new Currency("BDT", "Taka"));
                repository.save(new Currency("PLN", "Złoty"));
                repository.save(new Currency("DJF", "Frank dżibutyjski"));
                repository.save(new Currency("AUD", "Dolar Australijski"));
                repository.save(new Currency("GBP", "Brytyjski funt szterling"));
                repository.save(new Currency("KMF", "Frank Komoryjski"));
                repository.save(new Currency("BWP", "Pula"));
                repository.save(new Currency("MWK", "Kwacha zambijska"));
                repository.save(new Currency("NOK", "Korona norweska"));
                repository.save(new Currency("LKR", "Rupia lankijska"));
                repository.save(new Currency("OMR", "Rial omański"));
                repository.save(new Currency("UAH", "Hrywna"));
                repository.save(new Currency("CVE", "Escudo Republiki Zielonego Przylądka"));
                repository.save(new Currency("MGA", "Ariary"));
                repository.save(new Currency("THB", "Bat"));
                repository.save(new Currency("VEF", "Boliwar"));
                repository.save(new Currency("ILS", "Nowy Szekel"));
                repository.save(new Currency("AWG", "Florin arubański"));
                repository.save(new Currency("GTQ", "Quetzal"));
                repository.save(new Currency("SYP", "Funt syryjski"));
                repository.save(new Currency("EGP", "Funt Egipski"));
                repository.save(new Currency("FJD", "Dolar Fidżi"));
                repository.save(new Currency("AFN", "Afgani"));
                repository.save(new Currency("ARS", "Peso Argentyńskie"));
                repository.save(new Currency("BHD", "Dinar bahrajński"));
                repository.save(new Currency("BOV", "Mvdol"));
                repository.save(new Currency("GIP", "Funt Gibraltarski"));
                repository.save(new Currency("ALL", "Lek"));
                repository.save(new Currency("MDL", "Lej mołdawski"));
                repository.save(new Currency("SCR", "Rupia seszelska"));
                repository.save(new Currency("IDR", "Rupia"));
                repository.save(new Currency("MKD", "Denar Macedoński"));
                repository.save(new Currency("BOB", "Boliviano"));
                repository.save(new Currency("SBD", "Dolar Wysp Salomona"));
                repository.save(new Currency("VUV", "Vatu"));
                repository.save(new Currency("QAR", "Rial katarski"));
                repository.save(new Currency("NIO", "Córdoba"));
                repository.save(new Currency("TWD", "Dolar tajwański"));
                repository.save(new Currency("GNF", "Frank gwinejski"));
                repository.save(new Currency("SZL", "Lilangeni"));
                repository.save(new Currency("KYD", "Dolar Kajmański"));
                repository.save(new Currency("ISK", "Korona islandzka"));
                repository.save(new Currency("IRR", "Rial irański"));
                repository.save(new Currency("YER", "Rial jemeński"));
                repository.save(new Currency("CAD", "Kanadyjski Dolar"));
                repository.save(new Currency("HRK", "Kuna"));
                repository.save(new Currency("SEK", "Korona szwedzka"));
                repository.save(new Currency("BZD", "Dolar Belizeński"));
                repository.save(new Currency("MUR", "Rupia maurytyjska"));
                repository.save(new Currency("XPF", "Frank CFP"));
                repository.save(new Currency("DOP", "Peso dominikańskie"));
                repository.save(new Currency("KZT", "Tenge"));
                repository.save(new Currency("PEN", "Sol"));
                repository.save(new Currency("LRD", "Dolar liberyjski"));
                repository.save(new Currency("GYD", "Dolar Gujański"));
                repository.save(new Currency("LSL", "Loti"));
                repository.save(new Currency("BAM", "Marka Zamienna"));
                repository.save(new Currency("GHS", "Cedi"));
                repository.save(new Currency("ETB", "Birr"));
                repository.save(new Currency("LYD", "Dinar Libijski"));
                repository.save(new Currency("NGN", "Naira"));
                repository.save(new Currency("SOS", "Szyling somalijski"));
                repository.save(new Currency("AOA", "Kwanza"));
                repository.save(new Currency("SAR", "Rial saudyjski"));
                repository.save(new Currency("KES", "Szyling kenijski"));
                repository.save(new Currency("WST", "Tala"));
                repository.save(new Currency("HUF", "Forint"));
                repository.save(new Currency("TOP", "Pa’anga"));
                repository.save(new Currency("BTN", "Ngultrum"));
                repository.save(new Currency("RUB", "Rubel rosyjski"));
                repository.save(new Currency("NAD", "Dolar namibijski"));
                repository.save(new Currency("PHP", "Peso filipińskie"));
                repository.save(new Currency("CZK", "Korona Czeska"));
                repository.save(new Currency("IQD", "Dinar Iracki"));
                repository.save(new Currency("TND", "Dinar tunezyjski"));
                repository.save(new Currency("INR", "Rupia indyjska"));
                repository.save(new Currency("BYR", "Rubel białoruski"));
                repository.save(new Currency("PYG", "Guarani"));
                repository.save(new Currency("JMD", "Dolar Jamajski"));
                repository.save(new Currency("BBD", "Dolar Barbadosu"));
                repository.save(new Currency("SGD", "Dolar singapurski"));
                repository.save(new Currency("STN", "Dobra"));
                repository.save(new Currency("HKD", "Dolar hongkoński"));
                repository.save(new Currency("KRW", "Won"));
                repository.save(new Currency("DKK", "Korona Duńska"));
                repository.save(new Currency("PAB", "Balboa"));
                repository.save(new Currency("VND", "Dong"));
                repository.save(new Currency("RON", "Lej"));
                repository.save(new Currency("TTD", "Dolar Trynidadu i Tobago"));
                repository.save(new Currency("CDF", "Frank Kongijski"));
                repository.save(new Currency("MVR", "Rupia malediwska"));
                repository.save(new Currency("COP", "Peso kolumbijskie"));
                repository.save(new Currency("SRD", "Dolar surinamski"));
                repository.save(new Currency("ZMW", "Kwacha zambijska"));
                repository.save(new Currency("SHP", "Funt Świętej Heleny"));
                repository.save(new Currency("MAD", "Dirham marokański"));
            }
        };
    }
}